[workspace]
members = [
    "curio_core",
    "examples",
    "system_component_default_gameplay_macros/macro_events",
    "system_component_default_gameplay_macros/ecs_event",
    "system_component_default_gameplay_macros/ecs_system",
    "system_component_default_gameplay_macros/macro_component",
    "system_component_default_time",
    "system_component_default_input",
    "system_component_default_gameplay",
    "system_component_default_physics",
    "system_component_default_rendering",
    "system_component_default_networking",
    "system_component_default_gameplay_macros/macro_state",
    "system_component_default_rendering_macros/macro_render_feature_driver",
    "built_in_state",
    "system_component_default_gameplay_macros/macro_state_serialize",
]

[workspace.dependencies]
curio_core = { path = "curio_core" }
ecs_event = { path = "system_component_default_gameplay_macros/ecs_event" }
ecs_system = { path = "system_component_default_gameplay_macros/ecs_system" }
macro_component = { path = "system_component_default_gameplay_macros/macro_component"}
built_in_state = { path = "built_in_state" }
macro_events = { path = "system_component_default_gameplay_macros/macro_events" }
macro_state = { path = "system_component_default_gameplay_macros/macro_state" }
macro_state_serialize = { path = "system_component_default_gameplay_macros/macro_state_serialize" }
system_component_default_time = { path = "system_component_default_time" }
system_component_default_input = { path = "system_component_default_input" }
system_component_default_gameplay = { path = "system_component_default_gameplay" }
system_component_default_physics = { path = "system_component_default_physics" }
system_component_default_rendering = { path = "system_component_default_rendering" }
system_component_default_networking = { path = "system_component_default_networking" }

[workspace.package]
version = "0.1.0"
edition = "2021"
