[workspace]
resolver = "2"
members = [
    "curio_core",
    "curio_core_tests",
    "curio_engine",
    "system_component_default/gameplay",
    "system_component_default/gameplay_macros/impulse",
    "system_component_default/gameplay_macros/habit",
    "system_component_default/gameplay_macros/stimulant",
    "system_component_default/gameplay_macros/facet",
    "system_component_default/gameplay_macros/record",
    "system_component_default/gameplay_macros/record_serializable",
    "system_component_default/rendering",
    "system_component_default/rendering_macros/macro_render_feature_driver",
    "system_component_default/time",
    "system_component_default/physics",
    "system_component_default/networking",
    "system_component_default/animation",
    "system_component_default/input",
    "curio-editor/src-tauri",
    "optional_systems/camera",
    "optional_systems/rendering_static",
    "optional_systems/rendering_dynamic",
    "optional_systems/rendering_image",
    "optional_systems/rendering_text",
    "optional_systems/rendering_gizmos",
    "optional_systems/rendering",
    "optional_systems/collision",
    "optional_systems/lighting",
    "optional_systems/skybox",

]

[workspace.dependencies]
curio_engine = { path = "curio_engine" }
curio_core = { path = "curio_core" }
curio_core_tests = { path = "curio_core_tests" }
record = { path = "system_component_default/gameplay_macros/record" }
record_serializable = { path = "system_component_default/gameplay_macros/record_serializable" }
stimulant = { path = "system_component_default/gameplay_macros/stimulant" }
impulse = { path = "system_component_default/gameplay_macros/impulse" }
habit = { path = "system_component_default/gameplay_macros/habit" }
facet = { path = "system_component_default/gameplay_macros/facet" }
gameplay = { path = "system_component_default/gameplay" }
rendering = { path = "system_component_default/rendering" }
networking = { path = "system_component_default/networking" }
physics = { path = "system_component_default/physics" }
input = { path = "system_component_default/input" }
time = { path = "system_component_default/time" }
animation = { path = "system_component_default/animation" }
curio_editor = { path = "curio-editor/src-tauri" }
camera = { path = "optional_systems/camera" }
ext_rendering = { path = "optional_systems/rendering" }
rendering_static = { path = "optional_systems/rendering_static" }
rendering_dynamic = { path = "optional_systems/rendering_dynamic" }
rendering_image = { path = "optional_systems/rendering_image" }
rendering_text = { path = "optional_systems/rendering_text" }
rendering_gizmos = { path = "optional_systems/rendering_gizmos" }
lighting = { path = "optional_systems/lighting" }
collision = { path = "optional_systems/collision" }
skybox = { path = "optional_systems/skybox" }


[workspace.package]
version = "0.1.0"
edition = "2021"
