[package]
name = "lighting"
version = "0.1.0"
edition = "2024"


[dependencies]
habit = { workspace = true }
facet = { workspace = true }
gameplay = { workspace = true }
curio_core = { workspace = true }
record_serializable = { workspace = true }
serde = { version = "1.0.104", features = ["derive"] }
bytemuck = { version = "1.16", features = ["derive"] }
egui-wgpu = { version = "0.31.1", features = ["winit"] }
ctor = "0.8.0"
