#[derive(Clone, Hash, PartialEq, Eq)]
pub struct EventRunner<T, U>
where
    T: Clone + 'static,
    U: Clone + 'static,
{
    recievers: Vec<fn(&T, &mut U) -> Vec<T>>,
    queue: Vec<T>,
}

impl<T, U> EventRunner<T, U>
where
    T: Clone + 'static,
    U: Clone + 'static,
{
    pub fn new(recievers: Vec<fn(&T, &mut U) -> Vec<T>>) -> Self {
        Self { recievers, queue: Vec::new() }
    }

    pub fn enqueue(&mut self, event: &T) {
        self.queue.push(event.clone());
    }

    pub fn post_and_drain(&mut self, data: &mut U) {
        while let Some(event) = self.queue.pop() {
            for func in &self.recievers {
                let new_events = func(&event, data);
                // Optionally enqueue new events generated by handlers
                for new_event in new_events {
                    self.queue.push(new_event);
                }
            }
        }
    }
}
