[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
built_in_state = { path = "../built_in_state" }
curio_core = { path = "../curio_core" }
ecs_event = { path = "../system_component_default_gameplay_macros/ecs_event" }
ecs_system = { path = "../system_component_default_gameplay_macros/ecs_system" }
macro_component = { path = "../system_component_default_gameplay_macros/macro_component" }
futures = "0.3"
hecs = "0.10.5"
macro_events = { path = "../system_component_default_gameplay_macros/macro_events" }
macro_state = { path = "../system_component_default_gameplay_macros/macro_state" }
macro_state_serialize = { path = "../system_component_default_gameplay_macros/macro_state_serialize" }
mcts = "0.3.0"
pollster = "0.3"
rand = "0.9.1"
serde = { version = "1.0.104", features = ["derive", "rc"] }
system_component_default_gameplay = { path = "../system_component_default_gameplay" }
system_component_default_input = { path = "../system_component_default_input" }
system_component_default_networking = { path = "../system_component_default_networking" }
system_component_default_physics = { path = "../system_component_default_physics" }
system_component_default_rendering = { path = "../system_component_default_rendering" }
system_component_default_time = { path = "../system_component_default_time" }
winit = { version = "0.30", features = ["android-native-activity"] }
ctor = "0.2"
strum = "0.26"
strum_macros = "0.26"
