[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[dependencies]
hecs = "0.10.5"
inline_tweak = "1.2.2"
core = { path = "../core" }
built_in = { path = "../built_in" }
ecs_system = { path = "../ecs_system" }
ecs_event = { path = "../ecs_event" }
system_component_default_time = { path = "../system_component_default_time" }
system_component_default_input = { path = "../system_component_default_input" }
system_component_default_gameplay = { path = "../system_component_default_gameplay" }
system_component_default_physics = { path = "../system_component_default_physics" }
system_component_default_rendering = { path = "../system_component_default_rendering" }
ctor = "0.2"
intertrait = "0.2.2"
linkme = "=0.2.10"
pollster = "0.3"
