use curio_core::collections::{
    event_queue::{EventScope, IGameEvent},
    vector2_int::Vector2Int,
};
use std::{
    fmt::{Display, Formatter, Result},
    sync::Arc,
};
use stimulant::stimulant;

use crate::{
    cards::{card_dependencies::filled_card_response::FilledCardResponse, card_instance::CardInstance},
    exploration::exploration_path::{Exploration, Room},
    listeners::{listener_initialize_encounter::Encounter, listener_ui_set_mode::UITypes},
    state::{host::state_shop::Shop, state_ball_mode::BallModes, state_teams::Teams},
};

#[stimulant]
pub enum GameEvents {
    // an invalid default state
    #[default]
    Invalid,
    // to -> instance
    Begin,
    PointScored(Teams),
    TurnBegin(Teams),
    TurnEnd(Teams),
    PlayCard(i32, Arc<CardInstance>, FilledCardResponse),
    DidPlayCard(i32, Arc<CardInstance>, FilledCardResponse),
    ResetBoard(Teams),
    DrawCard(),
    DiscardCards(),
    MoveEntity(Vec<i32>, Vector2Int),
    OnDidSetBallMode(BallModes),
    InitializeExploration(Exploration),
    DidInitializeExploration(Exploration),
    InitializeEncounter(Encounter),
    FinalizeEncounter(Encounter),

    InitializeShop(Shop),
    FinalizeShop(Shop),

    DidInitializeEncounter(Encounter),
    DidEncounterPass,
    EncounterPassed,
    DidEncounterFail,
    EncounterFailed,
    ExplorationPickRoomStart(Exploration),
    ExplorationPickRoomComplete(Room),
    ExplorationDidPickRoomStart,
    ExplorationDidPickRoomComplete,
    ExplorationRoomEnter(Room),
    ExplorationRoomExit(Room),
    ExplorationDidRoomEnterShop(Room, Shop),
    ExplorationDidRoomExitShop(Room, Shop),
    ExplorationDidRoomEnterCombat(Room, Encounter),
    ExplorationDidRoomExitCombat(Room, Encounter),
    ExplorationDidRoomEnterHeal(Room),
    ExplorationDidRoomExitHeal(Room),
    RequestLeaveExplorationRoom,
    RequestHeal(i32),
    RequestPurchase(i32, i32),
    SetUIMode(UITypes),
    EnableUICombat,
    EnableUIHealing,
    EnableUIShop,
    DisableUICombat,
    DisableUIHealing,
    DisableUIShop,

    // to -> peer
    DidTurnEnd(Teams),
    DidTurnBegin(Teams),
    // to -> host
    RequestTurnEnd(i32),
    RequestMoveZPos(i32),
    RequestMoveZNeg(i32),
    RequestMoveXPos(i32),
    RequestMoveXNeg(i32),
    RequestUseManeuverPersistent(i32, i32, FilledCardResponse),
    RequestUseManeuverConsumable(i32, i32, FilledCardResponse),
}

impl IGameEvent for GameEvents {
    fn id() -> i32
    where
        Self: Sized + 'static,
    {
        0
    }
    fn ownership(&self) -> EventScope {
        match &self {
            GameEvents::Invalid => EventScope::Instance,
            GameEvents::DrawCard() => EventScope::Instance,
            GameEvents::DiscardCards() => EventScope::Instance,
            GameEvents::MoveEntity(_, _) => EventScope::Instance,
            GameEvents::Begin => EventScope::Instance,
            GameEvents::TurnEnd(_) => EventScope::Instance,
            GameEvents::TurnBegin(_) => EventScope::Instance,
            GameEvents::PlayCard(_, _, _) => EventScope::Instance,
            GameEvents::PointScored(_) => EventScope::Instance,
            GameEvents::ResetBoard(_) => EventScope::Instance,
            GameEvents::OnDidSetBallMode(_) => EventScope::Instance,
            GameEvents::RequestTurnEnd(_) => EventScope::ConnectedHost,
            GameEvents::RequestMoveZPos(_) => EventScope::ConnectedHost,
            GameEvents::RequestMoveZNeg(_) => EventScope::ConnectedHost,
            GameEvents::RequestMoveXPos(_) => EventScope::ConnectedHost,
            GameEvents::RequestMoveXNeg(_) => EventScope::ConnectedHost,
            GameEvents::RequestUseManeuverPersistent(_, _, _) => EventScope::ConnectedHost,
            GameEvents::RequestUseManeuverConsumable(_, _, _) => EventScope::ConnectedHost,
            GameEvents::DidTurnEnd(_) => EventScope::All,
            GameEvents::DidTurnBegin(_) => EventScope::All,
            GameEvents::InitializeEncounter(_) => EventScope::ConnectedHost,
            GameEvents::DidInitializeEncounter(_) => EventScope::All,
            GameEvents::InitializeExploration(_) => EventScope::ConnectedHost,
            GameEvents::DidInitializeExploration(_) => EventScope::All,
            GameEvents::EncounterPassed => EventScope::ConnectedHost,
            GameEvents::EncounterFailed => EventScope::ConnectedHost,
            GameEvents::ExplorationRoomEnter(_) => EventScope::ConnectedHost,
            GameEvents::ExplorationRoomExit(_) => EventScope::ConnectedHost,
            GameEvents::ExplorationDidRoomEnterCombat(_, _) => EventScope::All,
            GameEvents::ExplorationDidRoomExitCombat(_, _) => EventScope::All,
            GameEvents::SetUIMode(_) => EventScope::Instance,
            GameEvents::EnableUICombat => EventScope::Instance,
            GameEvents::EnableUIHealing => EventScope::Instance,
            GameEvents::EnableUIShop => EventScope::Instance,
            GameEvents::DisableUICombat => EventScope::Instance,
            GameEvents::DisableUIHealing => EventScope::Instance,
            GameEvents::DisableUIShop => EventScope::Instance,
            GameEvents::ExplorationDidRoomEnterHeal(_) => EventScope::All,
            GameEvents::ExplorationDidRoomExitHeal(_) => EventScope::All,
            GameEvents::RequestLeaveExplorationRoom => EventScope::ConnectedHost,
            GameEvents::RequestHeal(_) => EventScope::ConnectedHost,
            GameEvents::ExplorationPickRoomStart(_) => EventScope::ConnectedHost,
            GameEvents::ExplorationPickRoomComplete(_) => EventScope::ConnectedHost,
            GameEvents::ExplorationDidPickRoomStart => EventScope::All,
            GameEvents::ExplorationDidPickRoomComplete => EventScope::All,
            GameEvents::DidEncounterPass => EventScope::All,
            GameEvents::DidEncounterFail => EventScope::All,
            GameEvents::RequestPurchase(_, _) => EventScope::ConnectedHost,
            GameEvents::InitializeShop(_) => EventScope::ConnectedHost,
            GameEvents::ExplorationDidRoomEnterShop(_, _) => EventScope::All,
            GameEvents::ExplorationDidRoomExitShop(_, _) => EventScope::All,
            GameEvents::FinalizeEncounter(_) => EventScope::ConnectedHost,
            GameEvents::FinalizeShop(_) => EventScope::ConnectedHost,
            GameEvents::DidPlayCard(_, _, _) => EventScope::All,
        }
    }
}

impl Display for GameEvents {
    fn fmt(&self, f: &mut Formatter) -> Result {
        match self {
            GameEvents::Invalid => write!(f, "Invalid"),
            GameEvents::Begin => write!(f, "Begin"),
            GameEvents::TurnBegin(_) => write!(f, "TurnBegin"),
            GameEvents::TurnEnd(_) => write!(f, "TurnEnd"),
            GameEvents::PointScored(_) => write!(f, "PointScored"),
            GameEvents::ResetBoard(_) => write!(f, "ResetBoard"),
            GameEvents::PlayCard(_, _, _) => write!(f, "PlayCard"),
            GameEvents::RequestTurnEnd(_) => write!(f, "RequestTurnEnd"),
            GameEvents::DidTurnEnd(_) => write!(f, "DidTurnEnd"),
            GameEvents::DidTurnBegin(_) => write!(f, "DidTurnBegin"),
            GameEvents::RequestMoveZPos(_) => write!(f, "RequestMoveZPos"),
            GameEvents::RequestMoveZNeg(_) => write!(f, "RequestMoveZNeg"),
            GameEvents::RequestMoveXPos(_) => write!(f, "RequestMoveXPos"),
            GameEvents::RequestMoveXNeg(_) => write!(f, "OnDidSetBallMode"),
            GameEvents::OnDidSetBallMode(_) => write!(f, "RequestMoveXNeg"),
            GameEvents::RequestUseManeuverPersistent(_, _, _) => write!(f, "RequestUseManeuverPersistent"),
            GameEvents::RequestUseManeuverConsumable(_, _, _) => write!(f, "RequestUseManeuverConsumable"),
            GameEvents::DrawCard() => write!(f, "DrawCard"),
            GameEvents::DiscardCards() => write!(f, "DiscardCards"),
            GameEvents::MoveEntity(_, _) => write!(f, "MoveEntity"),
            GameEvents::InitializeEncounter(_) => write!(f, "InitializeEncounter"),
            GameEvents::DidInitializeEncounter(_) => write!(f, "DidInitializeEncounter"),
            GameEvents::InitializeExploration(exploration) => write!(f, "InitializeExploration"),
            GameEvents::DidInitializeExploration(exploration) => write!(f, "DidInitializeExploration"),
            GameEvents::EncounterPassed => write!(f, "EncounterPassed"),
            GameEvents::EncounterFailed => write!(f, "EncounterFailed"),
            GameEvents::ExplorationRoomEnter(_) => write!(f, "ExplorationRoomEnter"),
            GameEvents::ExplorationRoomExit(_) => write!(f, "ExplorationRoomExit"),
            GameEvents::ExplorationDidRoomEnterCombat(room, encounter) => write!(f, "ExplorationDidRoomEnterCombat"),
            GameEvents::ExplorationDidRoomExitCombat(room, encounter) => write!(f, "ExplorationDidRoomExitCombat"),
            GameEvents::SetUIMode(uitypes) => todo!(),
            GameEvents::EnableUICombat => todo!(),
            GameEvents::EnableUIHealing => todo!(),
            GameEvents::EnableUIShop => todo!(),
            GameEvents::DisableUICombat => todo!(),
            GameEvents::DisableUIHealing => todo!(),
            GameEvents::DisableUIShop => todo!(),
            GameEvents::ExplorationDidRoomEnterHeal(room) => todo!(),
            GameEvents::ExplorationDidRoomExitHeal(room) => todo!(),
            GameEvents::RequestLeaveExplorationRoom => todo!(),
            GameEvents::RequestHeal(_) => todo!(),
            GameEvents::ExplorationPickRoomStart(encounter) => todo!(),
            GameEvents::ExplorationPickRoomComplete(room) => todo!(),
            GameEvents::ExplorationDidPickRoomStart => todo!(),
            GameEvents::ExplorationDidPickRoomComplete => todo!(),
            GameEvents::DidEncounterPass => todo!(),
            GameEvents::DidEncounterFail => todo!(),
            GameEvents::RequestPurchase(_, _) => todo!(),
            GameEvents::InitializeShop(shop) => todo!(),
            GameEvents::ExplorationDidRoomEnterShop(room, shop) => todo!(),
            GameEvents::ExplorationDidRoomExitShop(room, shop) => todo!(),
            GameEvents::FinalizeEncounter(encounter) => todo!(),
            GameEvents::FinalizeShop(shop) => todo!(),
            GameEvents::DidPlayCard(_, card_instance, filled_card_response) => todo!(),
        }
    }
}
