[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[package]
name = "rendering"
version = "0.1.0"
edition = "2024"


[dependencies]
curio_core = { workspace = true }
egui = "0.31.1"
egui-winit = "0.31.1"
bytemuck = { version = "1.16", features = ["derive"] }
egui-wgpu = { version = "0.31.1", features = ["winit"] }
winit = { version = "0.30", features = ["android-native-activity"] }
